### ISSUE TITLE
Compare VEDA Dashboard CMIP6 with dedicated CMIP6 dashboard

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config#125]
The NEX-GDDP-CMIP6 dashboard: https://cmip6.surge.sh/ is the single-topic predecessor to VEDA Dashboards and should be superseded by a VEDA Dashboard for NEX-GDDP-CMIP6.

AC
- [ ] Statement (here) concluding on whether the VEDA NEX-GDDP-CMIP6 Dashboard is equivalent (especially in data content) to the standalone NEX-GDDP-CMIP6 Dashboard.

**Comment by anayeaye** [comment]
The CMIP6 dashboard: https://cmip6.surge.sh
VEDA ingest work: https://github.com/NASA-IMPACT/veda-data-pipelines/issues/204

**Comment by j08lue** [comment]
Might resurface for the CMIP6 PI objective. Closing for now. - [Support transformation and ingest of CMIP6](https://github.com/NASA-IMPACT/veda-architecture/issues/225)
