### ISSUE TITLE
Renamed resampling method parameter in TiTiler

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config#149]
In [many MDX files](https://github.com/NASA-IMPACT/delta-config/search?q=resampling_method), the TiTiler settings include a parameter `resampling_method`.

This parameter has been renamed to `resampling` in version `0.4.0a0` (2021-11-12): https://github.com/developmentseed/titiler/blob/23230e4ddb691a14346ac74ac9e6ae769dd04780/CHANGES.md#040a0-2021-11-12

So we should perhaps replace that throughout the files.

**Comment by Catalina-Moller** [comment]
We have tested this change verifying that in the mdx does not appear the parameter "resampling_method", but appears the parameter "resampling".  
But when testing the preview web of this change we have observed that in the affected datasets the rendering quality drops and there are some changes in the portions covering the layer, for example, in the dataset "Snow Water Equivalent Loss Projections" the lowest data of the layer are not shown while in the production environment it is possible to see them. 

**Dataset "Projections of Snow Water Equivalent Losses".**
Test environment: [URL](https://deploy-preview-174--visex.netlify.app/eis/datasets/snow-projections-diff/explore?position=-113.31%7C43.1787%7C4.25&datetime=2037-04-01T00%3A00%3A00.000Z)   
Production environment: [URL](https://www.earthdata.nasa.gov/dashboard/eis/datasets/snow-projections-diff/explore?position=-113.31%7C43.1787%7C4.25&datetime=2037-04-01T00%3A00%3A00.000Z)

**Dataset "Nitrogen Dioxide" layer "No2" (affects the representation):**
Test environment: [URL](https://deploy-preview-174--visex.netlify.app/air-quality/datasets/no2/explore?position=112.6337%7C30.3662%7C6.8&datetime=2016-01-01T00%3A00%3A00.000Z)
Production environment: [URL](https://www.earthdata.nasa.gov/dashboard/air-quality/datasets/no2/explore?position=112.6512%7C30.4854%7C6.97&datetime=2016-01-01T00%3A00%3A00.000Z)

We are not sure if this particular change is what produces the changes in the data sets, but we invite you to discuss these differences.
