### ISSUE TITLE
Configure CMIP6 datasets & discovery

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-config#153]
## Description

Based on content in the CMIP6 staging dashboard: https://cmip6.surge.sh/

2 datasets with multiple indicators (layers)
1 discovery
1 About page

Note, dates for these datasets are in the future
Also note, for the TAS Crossing Year layer, the date seems to be the dependent variable,, so it drives the map view. As opposed to the user selecting a date to view another metric.

## Acceptance Criteria
1. Content from the CMIP6 staging dashboard is displayed in VEDA Dashboard under a CMIP6 thematic area
2. CMIP6 staging dashboard is removed

**Comment by aboydnw** [comment]
@freitagb Just confirming, should CMIP6 be in the VEDA Dashboard and should it be its own thematic area?

**Comment by j08lue** [comment]
FYI the CMIP6 data is not fully loaded yet:
* Adding data https://github.com/NASA-IMPACT/veda-data-pipelines/issues/204 (in progress here https://github.com/NASA-IMPACT/veda-data-pipelines/pull/205)
* @anayeaye is tracking the ingestion here: https://github.com/NASA-IMPACT/veda-data-pipelines/issues/231

**Comment by aboydnw** [comment]
Thanks @j08lue 
Any updates on progress? Doesn't look like much movement in the tickets, is this still a focus for you all?

**Comment by j08lue** [comment]
We rolled the CMIP-6 ingestion over to the current sprint, but AFAIK are expecting to close it within that time.

**Comment by anayeaye** [comment]
@aboydnw I am planning to do some investigation of the sample CMIP6 data ingested into the dev catalog this sprint. I think we can reasonably finish evaluating whether or not the changes cause degraded stac-api/raster-api performance (CMIP6 was breaking for us in pgstac <v0.5) and if the metadata as defined are suitable for veda-config this sprint but I am not sure about the current state of the ingest pipelines for running the ingest for staging--that step could roll over.

**Comment by aboydnw** [comment]
Sounds good, thanks for the update. We don't have a real rush on this, just trying to plan out the next couple of sprints. Thanks!

**Comment by michaelgsuttles** [comment]
@anayeaye @j08lue Any update on this? No rush, but just checking; thanks!

**Comment by j08lue** [comment]
This is the ticket in progress https://github.com/NASA-IMPACT/veda-data-pipelines/issues/231. Let us discuss this during sprint planning on Monday - I'll remember to look in the "in progress" column.

**Comment by aboydnw** [comment]
Closing in favor of opening another ticket to explore options for visualization
