### ISSUE TITLE
Maps not loading when running dashboard locally

### ISSUE THREAD

**Issue by dfelikson** [NASA-IMPACT/veda-config#182]
I configured to run the VEDA dashboard locally but the maps don't load. Neither the Mapbox base layer nor the data shows up. Screenshot is below.

Side note: could this possibly be related to the issue here, as well: https://github.com/NASA-IMPACT/veda-config/issues/161.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/7451548/212131226-2c9d5a51-d1fd-4323-8067-e5a42736bf02.png">

**Comment by danielfdsilva** [comment]
@dfelikson Could you open the developer console and check if there are any errors?

**Comment by dfelikson** [comment]
@danielfdsilva - no errors that I can see:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/7451548/212209622-a71ab90b-c2d8-4392-9bc7-4cab1f08598e.png">

**Comment by danielfdsilva** [comment]
@dfelikson Apologies for the confusion. I mean the browser console.
From the screenshot it seems you are using firefox. You can access the console by pressing `cmd+opt+i` (on a mac), or by right clicking anywhere on the page, selecting `Inspect` and then select the `console` tab in the drawer that pops up.

<img width="627" alt="image" src="https://user-images.githubusercontent.com/1090606/212301969-d45a5c7e-d0ff-41c5-8882-77bd44e9c1b1.png">

You may need to refresh the page after opening the console for all the errors to be logged

**Comment by dfelikson** [comment]
Ah, thanks @danielfdsilva. I'm learning as I go, too, so I appreciate your help. It turns out that this was because of the Mapbox token. I have a Mapbox account and I was using a token that I had generated for my account. When I switched to the token that you had sent me a few days ago, the maps worked.

In general, when running the dashboard locally, should I be using Mapbox tokens that I, myself, have created? Or will I need to use tokens created by the VEDA project?

**Comment by dfelikson** [comment]
Got it! And just out of curiosity, are the COGs with the actual data coming
through Mapbox as well? Or are those served directly from the VEDA S3
bucket?

**Comment by danielfdsilva** [comment]
The COGs are accessed through the stac api and tiler, which read them from the S3 bucket.
The only thing from mapbox is the base map, and the country borders.

**Comment by danielfdsilva** [comment]
@dfelikson Will consider this resolved. Let us know if the issue pops up again.
