### ISSUE TITLE
User research for content configuration

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-config#221]
## Description
Our content configuration process is cumbersome for even our more technical users. The assumption right now is that this process will not scale as we begin to engage with more content creators for VEDA. In order to determine the best solution, we want to understand the workflow that our users go through to:
1. Create content for the dashboard
2. Create and ingest data into VEDA
3. Configure the dashboard with aforementioned content and data

## Acceptance Criteria
- [x] The problem space is sufficiently defined so that we understand the pain points from our users in the workflows listed above
- [x] We have gone through some prioritization where we identify the pain points that cause the most delay and frustration in this process, with the overall goal of making this process easy and quick
- [ ] [Stretch] We have worked with the team to ideate potential solutions to these high value pain points

**Comment by aboydnw** [comment]
@faustoperez Please check that I got this content correct ahead of sprint planning

**Comment by faustoperez** [comment]
Great, thanks @aboydnw, I would just add

- [ ] Understanding our user's experience creating data products and ingesting them into other platforms (NASA or non-NASA)

**Comment by faustoperez** [comment]
[Link to the Research Plan on Almanac](https://almanac.io/docs/dashboard-content-configuration-46rHxwLgqEUyza07qALSXGID17rt23V1?docView=Commenting)

**Comment by faustoperez** [comment]
### Interview Request Email Template - For NASA Impact requesting an interview
@jerikac 

Hi [scientist name],

The NASA IMPACT team is working to improve how scientists create and ingest data content on the VEDA dashboard to lower the entry barriers and grow the scientific community using VEDA. As part of this project, our agency partner, Development Seed, is running a series of interviews with Earth Scientists to learn more about how they use data products in their work.

As someone with valuable insights to share, a designer at Development Seed would like to spend 60-minutes with you in the following weeks via video conference call to ask you questions on various topics such as:

- What do you use NASA data products for?
- What’s your motivation for publishing datasets or discoveries on VEDA?
- Could you describe your process?

We appreciate you taking the time to share your knowledge with the project team. Your participation and feedback at this stage of the project will have a direct impact on how we improve our designs.

Thank you,
[Name]

**Comment by faustoperez** [comment]
Link to the [Miro board](https://miro.com/app/board/uXjVMWpGpcw=/?share_link_id=161659913570) with the research synthesis and the user journeys for both the discovery and dataset creation.

### Current user journey - Discovery creation
[Discovery creation journey.pdf](https://github.com/NASA-IMPACT/veda-config/files/11545845/Discovery.creation.journey.pdf)

### Current user journey - Dataset creation
[Dataset creation journey.pdf](https://github.com/NASA-IMPACT/veda-config/files/11545868/Dataset.creation.journey.pdf)

### Key takeaways and potential action points
[NASA VEDA Content Configuration Workflow Research Synthesis - Key takeaways.pdf](https://github.com/NASA-IMPACT/veda-config/files/11545879/NASA.VEDA.Content.Configuration.Workflow.Research.Synthesis.-.Key.takeaways.pdf)
