### ISSUE TITLE
Missing time_density property on sport-lis-vsm0_100cm-percentile dataset is causing date selection errors

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-config#236]
The **SPoRT Land Information System Overview** dataset is missing the dashboard:time_density property from the api response and it is causing the date selector to misbehave.

Video evidence
https://www.dropbox.com/xframe/s/iannxc5fmlkhjc0/sport.mp4?dl=0

cc @slesaad @smohiudd

**Comment by slesaad** [comment]
@danielfdsilva the `time_density` is not populated, so this should be fixed now
👀  https://deploy-preview-235--visex.netlify.app/eis/datasets/soil-moisture/explore?position=-96.005%7C40.4161%7C3.78&datetime=2016-09-06T00%3A00%3A00.000Z

**Comment by danielfdsilva** [comment]
@slesaad Yup. Behaving correctly. Closing
