### ISSUE TITLE
Review title and descriptions of each dataset and discovery to make sure they include relevant keyword

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-config#261]
# Description
Data catalog searching searches for the keyword only in the title and description of the dataset/discovery. This limits the search capabilities because not all relevant keywords exist in the title and description currently.

Thus, as a temporary solution, we want to go through each of the dataset/discovery and make sure the title and description cover as much of relevant keywords as possible while still forming a meaningful and relevant sentence.

An example case:
Searching for "methane" in the data catalog doesn't yield any results even though we have multiple methane datasets. All the gridded EPA datasets are methane emissions. 

It'll help to imagine what the user might search for to look for the dataset/discovery and make the updates accordingly.

# Acceptance Criteria
- [ ] Title and description for relevant datasets/discoveries are updated to include relevant keywords

**Comment by aboydnw** [comment]
Closing as not planned since it is a year old. If there is still a need, maybe we can look at https://github.com/NASA-IMPACT/veda-ui/issues/539
