### ISSUE TITLE
Fix nodata in ET suppression datasets

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config#269]
From @sahmad3:

> VEDA team, we are having a few updates done to the fire life cycle discovery (https://github.com/NASA-IMPACT/veda-config/pull/268). One issue I'm trying to address is the nodata values for the published ET suppression dataset (see the red ocean pixels in attached screenshot). Seems like the nodata values might not have been properly set while publishing the cog. Changing nodata in mdx didn't help, is there a way to mask out those red nodata pixels? 

The datasets that need this fix are:  

- `disalexi-etsuppression`
- `lis-etsuppression`
- `lis-tvegsuppression`

![image](https://github.com/NASA-IMPACT/veda-config/assets/3404817/26d1d82a-6cd3-449f-baa4-5ed44fc94a15)

**Comment by j08lue** [comment]
> Changing nodata in mdx didn't help

What should the `nodata` flag have been? Would be good to do a quick on-the-fly test to see whether passing `nodata` to TiTiler resolves it - then we just need to make it work through MDX. If that does not work, you need to produce a new version of the COG and upload it for us to replace the existing records with.

**Comment by j08lue** [comment]
From the image statistics (https://staging-raster.delta-backend.com/cog/statistics?url=s3://veda-data-store-staging/EIS/COG/Fire-Hydro/disalexi_etsuppression_2017.cog.tiff) it looks like `-1` is a very frequent value. That is probably the value used for `nodata`. But I am unable to get TiTiler to mask out those values.

![image](https://github.com/NASA-IMPACT/veda-config/assets/3404817/a1ffcab8-0446-482a-8ec5-50b98166d838)

https://staging-raster.delta-backend.com/cog/tiles/WebMercatorQuad/6/9/23@1x?url=s3%3A%2F%2Fveda-data-store-staging%2FEIS%2FCOG%2FFire-Hydro%2F%2Fdisalexi_etsuppression_2017.cog.tiff&bidx=1&rescale=0%2C1&colormap_name=viridis

The best would be to cloud-optimize the rasters again with `rio cogeo create --nodata=-1 <input.tif> <output.tif>` (see [docs](https://cogeotiff.github.io/rio-cogeo/CLI/#create)), then we also get an intact version in our storage and do not just patch the visualization in the Dashboard.

Please note: it is probably not sufficient to just set the `nodata` flag on the rasters. You need to cloud-optimize again so the overviews get created correctly.

**Comment by sahmad3** [comment]
The COGs have been updated with `nodata` set to `-1.0 `

Here are the 6 tiffs that need to republish
```
s3://veda-data-store-staging/EIS/COG/Fire-Hydro/disalexi_etsuppression_20{17..20}.cog.tiff
s3://veda-data-store-staging/EIS/COG/Fire-Hydro/lis_etsuppression_2020.cog.tiff
s3://veda-data-store-staging/EIS/COG/Fire-Hydro/lis_tvegsuppression_2020.cog.tiff
```

**Comment by j08lue** [comment]
> The COGs have been updated

Are those the same URIs as before - did you delete the old files and upload new ones with the same names?

If the file changed, it looks like it still has the same rendering issue where ocean areas are not transparent:

![image](https://github.com/NASA-IMPACT/veda-config/assets/3404817/7f9b81f9-7a54-4a25-90b9-d2c6f2458283)

https://staging-raster.delta-backend.com/cog/tiles/WebMercatorQuad/6/9/23@1x?url=s3://veda-data-store-staging/EIS/COG/Fire-Hydro/disalexi_etsuppression_2017.cog.tiff&bidx=1&rescale=0%2C1&colormap_name=viridis

**Comment by sahmad3** [comment]
Yes they are the same URLs with old ones replaced by new. I can see nodata now set to -1.0 in gdalinfo. Maybe once these are republished, setting nodata in MDX to -1 can help?

**Comment by j08lue** [comment]
I had a look at your files. Turns out the valid data range seems to be from -1 to 1 (with some outliers existing) and the `nodata` value used is in fact `NaN`.

https://gist.github.com/j08lue/cb81deea35b06f2f9117b09f4f2dfd26

![image](https://github.com/NASA-IMPACT/veda-config/assets/3404817/95961eac-4d7d-4c81-b1fe-ea08338a3ef7)

Setting `nodata=nan` with TiTiler fixes the view:

![image](https://github.com/NASA-IMPACT/veda-config/assets/3404817/9692465b-ad5b-42f1-9026-15c8e909fbd9)

https://staging-raster.delta-backend.com/cog/tiles/WebMercatorQuad/6/9/23@1x?url=s3://veda-data-store-staging/EIS/COG/Fire-Hydro/disalexi_etsuppression_2017.cog.tiff&bidx=1&rescale=-1,1&colormap_name=viridis&nodata=nan
 

But ideally you should publish new files where the `nodata` flag is set to NaN in the files or you replaced values and flag with a different value (some people don't like NaN as `nodata` for some reason). At the bottom of the notebook I shared above, I put in some code you can use to fix the nodata pixel values and use -9999.

NB: To be able to read the files directly from S3, feel free to use our JupyterHub service at https://nasa-veda.2i2c.cloud/ - I see you already have access to that.

**Comment by sahmad3** [comment]
Yes but it is updated in the PR #268 

https://github.com/NASA-IMPACT/veda-config/blob/aa78bd86c6e88237fd71286a28123dc35afb43bc/datasets/disalexi-etsuppression.data.mdx?plain=1#LL28C6-L28C6

The deploy preview here looks fine: https://deploy-preview-268--visex.netlify.app/discoveries/fire-life-cycle

Can the VEDA team get this PR accepted?
