### ISSUE TITLE
Configure GST CO2 dataset for the dashboard

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-config#290]
Following https://github.com/NASA-IMPACT/veda-data-pipelines/issues/346

**Comment by slesaad** [comment]
PR up at https://github.com/NASA-IMPACT/veda-config/pull/291

Following up with the data providers to ask what variables to show in the explore page.

**Comment by aboydnw** [comment]
@slesaad I don't think I see this in the Earthdata dashboard or in GHG. Do we know what happened with this?

**Comment by slesaad** [comment]
@aboydnw i think this is the one - https://earth.gov/ghgcenter/data-catalog/oco2-mip-co2budget-yeargrid-v1 ?
