### ISSUE TITLE
Set up a preview for the Exploration & Analysis feature on VEDA Dashboard

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config#359]
Similar to https://github.com/NASA-IMPACT/veda-config-ghg/pull/217, we would like to have a feature preview (not for merging yet) of the Exploration & Analysis interface.

There are a few concrete cases where that interface would be useful for exploring VEDA Dashboard datasets and this preview could also lead the way to a first proper staging and later production deployment of the feature.

## Acceptance criteria

- [x] A Netlify preview featuring the E&A interface for the VEDA Dashboard datasets is up

**Comment by hanbyul-here** [comment]
The preview was generated in this PR: https://github.com/NASA-IMPACT/veda-config/pull/360
