### ISSUE TITLE
Demo comparison of Black Marble dataset versions in E&A environment

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config#364]
A team is working on a new version of Black Marble products in the `hd-blackmarble-nightlights` [collection](https://radiantearth.github.io/stac-browser/#/external/staging-stac.delta-backend.com/collections/hd-blackmarble-nightlights), which will eventually replace the current version in the `nightlights-hd-1band` [collection](https://radiantearth.github.io/stac-browser/#/external/staging-stac.delta-backend.com/collections/nightlights-hd-1band). 

For validating the two versions against each other, it would be great to have both available in a preview E&A environment. This would also make a good real-world test case for that interface.

## Acceptance criteria

- [x] Deployed a preview with the E&A environment and both of these collections / Datasets configured and shared with @freitagb

**Comment by freitagb** [comment]
Currently have a [netlify preview](https://deploy-preview-361--visex.netlify.app/data-catalog/hd-blackmarble-nightlights/explore?projection=mercator%7C%7C&basemapid=satellite&datetime=2023-01-24T00%3A00%3A00.000Z&position=22.3538%7C32.7332%7C9.31) for testing that output from the updated algorithm complies with and is performant in the VEDA dashboard.

**Comment by j08lue** [comment]
- https://github.com/NASA-IMPACT/veda-config/pull/361

**Comment by j08lue** [comment]
Ah, so all we would need is to enable E&A on that preview, @freitagb?

We could easily do that by just merging the `preview-ae` branch from #360 into #361, which updates the VEDA UI submodule and sets the feature flag to enable A&E. Let me know if I should do that.

**Comment by freitagb** [comment]
Yep! Whatever is easiest. We wanted to get the data in there just to troubleshoot the algorithm we're implementing.

**Comment by j08lue** [comment]
Done, now building the preview. 🤞

**Comment by j08lue** [comment]
Hmm, Nighlights EJ [works in E&A](https://deploy-preview-361--visex.netlify.app/exploration?datasets=%5B%7B%22id%22%3A%22nightlights-hd-1band%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22min%22%2C%22label%22%3A%22Min%22%2C%22chartLabel%22%3A%22Min%22%2C%22themeColor%22%3A%22infographicA%22%7D%2C%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Avg%22%2C%22themeColor%22%3A%22infographicB%22%7D%2C%7B%22id%22%3A%22max%22%2C%22label%22%3A%22Max%22%2C%22chartLabel%22%3A%22Max%22%2C%22themeColor%22%3A%22infographicC%22%7D%2C%7B%22id%22%3A%22std%22%2C%22label%22%3A%22St+Deviation%22%2C%22chartLabel%22%3A%22STD%22%2C%22themeColor%22%3A%22infographicD%22%7D%2C%7B%22id%22%3A%22median%22%2C%22label%22%3A%22Median%22%2C%22chartLabel%22%3A%22Median%22%2C%22themeColor%22%3A%22infographicE%22%7D%5D%7D%7D%2C%7B%22id%22%3A%22nightlights-hd-monthly%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22min%22%2C%22label%22%3A%22Min%22%2C%22chartLabel%22%3A%22Min%22%2C%22themeColor%22%3A%22infographicA%22%7D%2C%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Avg%22%2C%22themeColor%22%3A%22infographicB%22%7D%2C%7B%22id%22%3A%22max%22%2C%22label%22%3A%22Max%22%2C%22chartLabel%22%3A%22Max%22%2C%22themeColor%22%3A%22infographicC%22%7D%2C%7B%22id%22%3A%22std%22%2C%22label%22%3A%22St+Deviation%22%2C%22chartLabel%22%3A%22STD%22%2C%22themeColor%22%3A%22infographicD%22%7D%2C%7B%22id%22%3A%22median%22%2C%22label%22%3A%22Median%22%2C%22chartLabel%22%3A%22Median%22%2C%22themeColor%22%3A%22infographicE%22%7D%5D%7D%7D%5D&date=2021-08-08T22%3A00%3A00.000Z), but not Nightlights Monthly.

**Comment by j08lue** [comment]
Seems to work now.
