### ISSUE TITLE
Check for broken links to former thematic areas

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config#368]
#367 fixes a link that was still formatted as `/stories/<thematic-area>/<story-id>`.

Are there maybe more broken links since we removed thematic areas?

Should be a simple regex search exercise (`stories\/[^a-zA-Z0-9_]\/.*` or so?).

Also applies to datasets, actually. For those, the thematic area route could be replaced by a taxonomy search in the Data Catalog, if possible.

## Acceptance criteria

- [ ] Checked whether there are links in stories and dataset overview pages that include thematic areas
- [ ] Fixed any broken links discovered

**Comment by aboydnw** [comment]
Going to close this based on the linked PR
