### ISSUE TITLE
What to do with the Recent Fires story / custom UI?

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config#384]
We have a [Dashboard story showcasing the FireNRT dataset](https://www.earthdata.nasa.gov/dashboard/stories/recent-fires) via an embedded [custom UI](https://github.com/NASA-IMPACT/veda-interactive-fire): 

However, the embedded UI takes a very long time to load and the story is very bare-bones.

## Acceptance criteria

- [x] Answered whether we want to keep the story and UI as-is, should invest in a revamp, or take it down

**Comment by j08lue** [comment]
Pinging @siddharth0248 (since you recently mentioned this, I think) and @mccabete. 🙏

**Comment by mccabete** [comment]
I think @siddharth0248 took this down. I think we may come back to it, but it made sense for it not to be "live".
