### ISSUE TITLE
Replace broken links to /datasets with /data-catalog

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config#385]
Some stories contain links to `/datasets`, which changed to `/data-catalog` a while back.

For example:

https://github.com/NASA-IMPACT/veda-config/blob/b7ab7e5eec5f26c65e317986c7f617fee0431e74/datasets/global-reanalysis-da.data.mdx?plain=1#L371

## Acceptance criteria

- [x] Searched through data story and dataset overview MDX files and fixed these broken links

**Comment by Franqsanz** [comment]
Hi @j08lue, I would like to work on this problem, the change should be done on all `mdx` files?

**Comment by j08lue** [comment]
Great, yes, please!
