### ISSUE TITLE
Deploy earthdata.nasa.gov/dashboard on 5/21 Tue

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/veda-config#397]

**Comment by sandrahoang686** [comment]
**Steps:**
1. Create changelog from Develop against Main branch
2. Create a new branch to bump version tag to v0.15.2 against develop and include Changelog as part of description.
3. Create PR from Develop against Main, include changelog as part of description
4. Once merged, cut tagged release against Main branch with changelog

**Comment by aboydnw** [comment]
@hanbyul-here @sandrahoang686 @dzole0311 I added https://github.com/NASA-IMPACT/veda-config/issues/395 to the sprint, assuming it is part of this release. Feel free to drop it out of the sprint if that's not the case, though. I just saw it when reviewing the backlog.
