### ISSUE TITLE
Add custom javascript tag to add DAP script block

### ISSUE THREAD

**Issue by amarouane-ABDELHAK** [NASA-IMPACT/veda-config#459]
**Description** 
In response to a memo directing agencies to ensure that GSA’s [Digital Analytics Program (DAP)](https://nasa.sharepoint.com/sites/webservices/SitePages/Google%20Analytics%20DAP.aspx) tracking code is installed on all public-facing sites to enable reporting of web traffic metrics, we need to add a custom script tag to the header for the dashboard served under earthdata.nasa.gov/dashboard.

`<script async="true" type="text/javascript" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=NASA&subagency=HQ" id="_fed_an_ua_tag"></script>`

The script block above must be inserted in the <head> of all public-facing pages on the website.
The best location for the script block is directly before the closing </head>.
The above example is the minimum required script block. Additional DAP parameters (e.g., “yt=true”, “dclink=true”) may be added at the website owner’s discretion.
For more info, please follow the instructions and examples in GSA’s [DAP Quick Guide](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdigital-analytics-program%2Fgov-wide-code%2Fblob%2Fmaster%2Fdocumentation%2FGSA%2520DAP%25204.1%2520-%2520Quick%2520Guide.pdf&data=05%7C02%7Cnatasha.r.pinol%40nasa.gov%7C2e7990797e3f4f4abc9308dc2cabb6da%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638434363219631314%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=nQj8oSLneFFaNygqwHEWWHYeljLaCwv9GgYpE%2FAwrRQ%3D&reserved=0) starting on page 7.

**Comment by aboydnw** [comment]
@amarouane-ABDELHAK I see this added to the .env file in [this PR](https://github.com/US-GHG-Center/veda-config-ghg/pull/310/files)

Is that all that needs to happen in veda-config?

cc @hanbyul-here 

```
# Add DAP script block with tracking code for the DAP compliance. 
# Every public-facing NASA website must install the DAP tracking code on all public-facing pages.
# This federal requirement was first published in OMB M-17-06 (issued in 2016) and was re-issued in OMB M-23-22 in September 2023. 

CUSTOM_SCRIPT_SRC=https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=NASA&subagency=HQ
CUSTOM_SCRIPT_ID=_fed_an_ua_tag
```
