### ISSUE TITLE
Configure Trilateral Agriculture Story

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-config#84]
## Description
NASA has converted the story originally written for the Trilateral dashboard to be compatible for the VEDA Dashboard. After configuring the VEDA dashboard to reveal the previously ingested Trilateral datasets, we would like to start configuring stories for the VEDA Dashboard in these thematic areas.

## Acceptance Criteria
- [ ] Agriculture story is configured with the appropriate UI elements

Story doc: https://drive.google.com/drive/folders/1GTlYd0ixuRm-hfFoql8-2j5rY1H6swYy?usp=sharing

**Comment by aboydnw** [comment]
@danielfdsilva I updated the google drive link in this story. I created a folder that holds the story and associated images and csv files. No changes to the story, just additional files.

**Comment by danielfdsilva** [comment]
@aboydnw I has extracted the images and created a draft of the story. (https://github.com/NASA-IMPACT/delta-config/pull/99). Not sure how we can use the CSVs. They don't seem to contain the data needed for the charts.
