### ISSUE TITLE
Configure Thematic Area via UI

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-config#97]
## Description

A followup to https://github.com/NASA-IMPACT/delta-config/issues/87
The goal of this ticket is to configure a new thematic area, metadata and content.

## Acceptance Criteria
- [ ] Given I have access to the configuration UI, when I create a new thematic area in the configuration UI then I can see that thematic area with the configured title, cover image and description text appearing
- [ ] Given I have access to the configuration UI, when I create a new thematic area in the configuration UI then I can see the About page text for that thematic area

**Comment by danielfdsilva** [comment]
Thematic areas no longer exist
